const types = {
  TRACK_ACTIVATION: "TRACK_ACTIVATION",
  TRACK_ACTIVATION_BUTTON: "TRACK_ACTIVATION_BUTTON",
  TRACK_SPECIFICATION_BUTTON: "TRACK_SPECIFICATION_BUTTON",
  TRACK_STATUS_BUTTON: "TRACK_STATUS_BUTTON"
};

const statusTypes = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE"
};

export default { types, statusTypes };
