sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
script:
- npm test
- npm run build
after_success: npx codecov
branches:
  only: master
